DELETE FROM EMPLOYEE_TRAINING;
DELETE FROM EMPLOYEE_COMPUTER;
DELETE FROM EMPLOYEE;
DELETE FROM PAYMENT_TYPE;
DELETE FROM CUSTOMER_ORDER;
DELETE FROM PRODUCTS_REQUEST;
DELETE FROM EMPLOYEE_TYPE;
DELETE FROM PRODUCT;
DELETE FROM TRAINING_PROGRAM;
DELETE FROM PRODUCT_TYPE;
DELETE FROM DEPARTMENT;
DELETE FROM CUSTOMER;
DELETE FROM COMPUTER;

DROP TABLE IF EXISTS TRAINING_PROGRAM;
DROP TABLE IF EXISTS COMPUTER;
DROP TABLE IF EXISTS EMPLOYEE_TYPE;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS EMPLOYEE_TRAINING;
DROP TABLE IF EXISTS EMPLOYEE_COMPUTER;
DROP TABLE IF EXISTS PAYMENT_TYPE;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CUSTOMER_ORDER;
DROP TABLE IF EXISTS PRODUCTS_REQUEST;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS PRODUCT_TYPE;

CREATE TABLE `TRAINING_PROGRAM` (
	`TRAINING_PROGRAM_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME` TEXT NOT NULL,
	`START_DATE`  TEXT NOT NULL,
	`END_DATE`  TEXT NOT NULL,
	`MAX_ATTENDEES` INTEGER NOT NULL
)

INSERT INTO TRAINING_PROGRAM VALUES (null, 'CUSTOMER_SERVICE', 'MARCH 12, 2017', 'MARCH 17, 2017', 15);
INSERT INTO TRAINING_PROGRAM VALUES (null, 'LEADERSHIP', 'JANUARY 23, 2017', 'JANUARY 25, 2017', 15);
INSERT INTO TRAINING_PROGRAM VALUES (null, 'COMMUNICATION', 'FEBRUARY 01, 2017', 'FEBRUARY 05, 2017', 15);
INSERT INTO TRAINING_PROGRAM VALUES (null, 'EEO', 'APRIL 12, 2017', 'APRIL 17, 2017', 15);
INSERT INTO TRAINING_PROGRAM VALUES (null, 'EMERGENCY_MANAGEMENT', 'MAY 2, 2017', 'MAY 7, 2017', 15);

create table `PAYMENT_TYPE`(
	`PAYMENT_TYPE_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TYPE` TEXT NOT NULL,
	`ACCOUNT_NUMBER` TEXT NOT NULL,
	`CUSTOMER_ID` INTEGER NOT NULL,
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
)

INSERT INTO PAYMENT_TYPE  
  SELECT null, 'PAYPAL', '9847394958', CUSTOMER_ID
  FROM CUSTOMER C
  WHERE C.LAST_NAME = 'CZEH';

  INSERT INTO PAYMENT_TYPE  
  SELECT null, 'CREDIT', '123456789012', CUSTOMER_ID
  FROM CUSTOMER C
  WHERE C.LAST_NAME = 'GABRIEL';

  INSERT INTO PAYMENT_TYPE  
  SELECT null, 'CHECKING ACCOUNT', '13579073', CUSTOMER_ID
  FROM CUSTOMER C
  WHERE C.LAST_NAME = 'BROWN';

  INSERT INTO PAYMENT_TYPE  
  SELECT null, 'CREDIT', '98743028', CUSTOMER_ID
  FROM CUSTOMER C
  WHERE C.LAST_NAME = 'ANDERSON';

  INSERT INTO PAYMENT_TYPE  
  SELECT null, 'PAYPAL', 'MF839284MR', CUSTOMER_ID
  FROM CUSTOMER C
  WHERE C.LAST_NAME = 'KIM';

CREATE TABLE `COMPUTER` (
	`COMPUTER_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PURCHASE_DATE` TEXT NOT NULL,
	`DECOMISSION_DATE` TEXT NOT NULL
)
INSERT INTO COMPUTER VALUES (null, 'JANUARY 1, 2016', 'JANUARY 1, 2020');
INSERT INTO COMPUTER VALUES (null, 'FEBRUARY 1, 2015', 'FEBRUARY 1, 2019');
INSERT INTO COMPUTER VALUES (null, 'MARCH 1, 2014', 'MARCH 1, 2018');
INSERT INTO COMPUTER VALUES (null, 'APRIL 1, 2013', 'APRIL 1, 2017');
INSERT INTO COMPUTER VALUES (null, 'JANUARY 1, 2017', 'JANUARY 1, 2021');


create table `CUSTOMER`(
	`CUSTOMER_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`FIRST_NAME` TEXT NOT NULL,
	`LAST_NAME` TEXT NOT NULL,
	`DATE_CREATED` TEXT NOT NULL,
	`DEACTIVATION_DATE` TEXT NOT NULL
)

INSERT INTO CUSTOMER VALUES (null, 'SIMONE', 'GABRIEL', 'JANUARY 13, 2017', 'SEPTEMBER 12, 2017');
INSERT INTO CUSTOMER VALUES (null, 'ROGER', 'ANDERSON', 'JANUARY 12, 2017', 'SEPTEMBER 11, 2017');
INSERT INTO CUSTOMER VALUES (null, 'CRAIG', 'KIM', 'JANUARY 11, 2017', 'SEPTEMBER 10, 2017');
INSERT INTO CUSTOMER VALUES (null, 'ANGELA', 'BROWN', 'JANUARY 10, 2017', 'SEPTEMBER 09, 2017');
INSERT INTO CUSTOMER VALUES (null, 'LAZSLO', 'CZEH', 'JANUARY 09, 2017', 'SEPTEMBER 08, 2017');

CREATE TABLE `CUSTOMER_ORDER` (
	`ORDER_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`STATUS`  TEXT NOT NULL,
	`CUSTOMER_ID`  INTEGER NOT NULL,
	`PAYMENT_TYPE` INTEGER NOT NULL,
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`),
	FOREIGN KEY(`PAYMENT_TYPE`) REFERENCES `PAYMENT_TYPE` (`PAYMENT_TYPE_ID`)
)

INSERT INTO CUSTOMER_ORDER  
SELECT null, 'ACTIVE', C.CUSTOMER_ID, P.PAYMENT_TYPE_ID
FROM CUSTOMER C, PAYMENT_TYPE P
WHERE C.LAST_NAME = 'KIM' AND P.CUSTOMER_ID = C.CUSTOMER_ID  

INSERT INTO CUSTOMER_ORDER  
SELECT null, 'ACTIVE', C.CUSTOMER_ID, P.PAYMENT_TYPE_ID
FROM CUSTOMER C, PAYMENT_TYPE P
WHERE C.LAST_NAME = 'BROWN' AND P.CUSTOMER_ID = C.CUSTOMER_ID  

INSERT INTO CUSTOMER_ORDER  
SELECT null, 'ACTIVE', C.CUSTOMER_ID, P.PAYMENT_TYPE_ID
FROM CUSTOMER C, PAYMENT_TYPE P
WHERE C.LAST_NAME = 'ANDERSON' AND P.CUSTOMER_ID = C.CUSTOMER_ID  

INSERT INTO CUSTOMER_ORDER  
SELECT null, 'ACTIVE', C.CUSTOMER_ID, P.PAYMENT_TYPE_ID
FROM CUSTOMER C, PAYMENT_TYPE P
WHERE C.LAST_NAME = 'CZEH' AND P.CUSTOMER_ID = C.CUSTOMER_ID  

INSERT INTO CUSTOMER_ORDER  
SELECT null, 'ACTIVE', C.CUSTOMER_ID, P.PAYMENT_TYPE_ID
FROM CUSTOMER C, PAYMENT_TYPE P
WHERE C.LAST_NAME = 'GABRIEL' AND P.CUSTOMER_ID = C.CUSTOMER_ID

CREATE TABLE `PRODUCT_TYPE` (
	`PRODUCT_TYPE_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME`  TEXT NOT NULL
)
INSERT INTO PRODUCT_TYPE VALUES (null, 'ELECTRONICS');
INSERT INTO PRODUCT_TYPE VALUES (null, 'CONSUMER GOODS');
INSERT INTO PRODUCT_TYPE VALUES (null, 'APPLIANCES');
INSERT INTO PRODUCT_TYPE VALUES (null, 'GROCERIES');
INSERT INTO PRODUCT_TYPE VALUES (null, 'SPORTING GOODS');


CREATE TABLE `PRODUCT` (
	`PRODUCT_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PRICE`  TEXT NOT NULL,
	`TITLE` TEXT NOT NULL,
	`DESCRIPTION` TEXT NOT NULL,
	`CREATED_BY` INTEGER NOT NULL,
	`PRODUCT_TYPE` INTEGER NOT NULL,
	FOREIGN KEY(`CREATED_BY`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`),
	FOREIGN KEY(`PRODUCT_TYPE`) REFERENCES `PRODUCT_TYPE` (`PRODUCT_TYPE_ID`)
)


INSERT INTO PRODUCT  
SELECT null, '29.99', 'EXTERNAL BATTERY', 'UNIVERSAL LAPTOP EXTERNAL BATTERY', CUSTOMER_ID, PRODUCT_TYPE
FROM CUSTOMER C, PRODUCT_TYPE P
WHERE C.LAST_NAME = 'GABRIEL' AND P.NAME = 'ELECTRONICS';

INSERT INTO PRODUCT  
SELECT null, '29.99', 'EXTERNAL BATTERY', 'UNIVERSAL LAPTOP EXTERNAL BATTERY', C.CUSTOMER_ID, P.PRODUCT_TYPE_ID
FROM CUSTOMER C, PRODUCT_TYPE P
WHERE C.LAST_NAME = 'GABRIEL' AND P.NAME = 'ELECTRONICS';

INSERT INTO PRODUCT  
SELECT null, '19.99', 'FOOTBALL', 'NFL REGULATION SIZED', C.CUSTOMER_ID, P.PRODUCT_TYPE_ID
FROM CUSTOMER C, PRODUCT_TYPE P
WHERE C.LAST_NAME = 'ANDERSON' AND P.NAME = 'SPORTING GOODS';

INSERT INTO PRODUCT  
SELECT null, '39.99', 'NESPRESSO Z71', 'ESPRESSO MAKER', C.CUSTOMER_ID, P.PRODUCT_TYPE_ID
FROM CUSTOMER C, PRODUCT_TYPE P
WHERE C.LAST_NAME = 'KIM' AND P.NAME = 'APPLIANCES'; 

INSERT INTO PRODUCT  
SELECT null, '49.99', 'WINE', 'BAREFOOT ZINFANDEL', C.CUSTOMER_ID, P.PRODUCT_TYPE_ID
FROM CUSTOMER C, PRODUCT_TYPE P
WHERE C.LAST_NAME = 'BROWN' AND P.NAME = 'GROCERIES';  

INSERT INTO PRODUCT  
SELECT null, '59.99', 'RAZOR', 'GILLETE HANDHELD', C.CUSTOMER_ID, P.PRODUCT_TYPE_ID
FROM CUSTOMER C, PRODUCT_TYPE P
WHERE C.LAST_NAME = 'CZEH' AND P.NAME = 'CONSUMER GOODS';

CREATE TABLE `EMPLOYEE_TYPE` (
	`EMPLOYEE_TYPE_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME` TEXT NOT NULL
)
INSERT INTO EMPLOYEE_TYPE VALUES (null, 'SUPERVISOR');
INSERT INTO EMPLOYEE_TYPE VALUES (null, 'NON_SUPERVISOR');

CREATE TABLE `DEPARTMENT` (
	`DEPARTMENT_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`BUDGET`  INTEGER NOT NULL,
	`NAME` TEXT NOT NULL,
)

INSERT INTO DEPARTMENT VALUES(NULL, 1000000, 'HUMAN_RESOURCES');
INSERT INTO DEPARTMENT VALUES(NULL, 900000, 'SERVICE');
INSERT INTO DEPARTMENT VALUES(NULL, 800000, 'MARKETING');
INSERT INTO DEPARTMENT VALUES(NULL, 700000, 'SALES');
INSERT INTO DEPARTMENT VALUES(NULL, 600000, 'IT');

CREATE TABLE `EMPLOYEE` (
	`EMPLOYEE_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME`  TEXT NOT NULL,
	`DEPARTMENT_ID`  INTEGER NOT NULL,
	`TRAINING_PROGRAM_ID`  INTEGER NOT NULL,
	`EMPLOYEE_TYPE`  INTEGER NOT NULL,
	FOREIGN KEY(`DEPARTMENT_ID`) REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`),
	FOREIGN KEY(`TRAINING_PROGRAM_ID`) REFERENCES `TRAINING_PROGRAM` (`TRAINING_PROGRAM_ID`),
	FOREIGN KEY(`EMPLOYEE_TYPE`) REFERENCES `EMPLOYEE_TYPE` (`EMPLOYEE_TYPE_ID`)
)

INSERT INTO EMPLOYEE 
SELECT null, 'RICHMOND WALTERS', D.DEPARTMENT_ID, T.TRAINING_PROGRAM_ID, E.EMPLOYEE_TYPE_ID
FROM DEPARTMENT D, TRAINING_PROGRAM T, EMPLOYEE_TYPE E
WHERE D.NAME = 'HUMAN_RESOURCES' AND T.NAME = 'EEO' AND E.NAME = 'SUPERVISOR'

INSERT INTO EMPLOYEE 
SELECT null, 'ALEXANDRIA CARROLL', D.DEPARTMENT_ID, T.TRAINING_PROGRAM_ID, E.EMPLOYEE_TYPE_ID
FROM DEPARTMENT D, TRAINING_PROGRAM T, EMPLOYEE_TYPE E
WHERE D.NAME = 'SALES' AND T.NAME = 'CUSTOMER_SERVICE' AND E.NAME = 'SUPERVISOR'

INSERT INTO EMPLOYEE 
SELECT null, 'MONTGOMERY SNELL', D.DEPARTMENT_ID, T.TRAINING_PROGRAM_ID, E.EMPLOYEE_TYPE_ID
FROM DEPARTMENT D, TRAINING_PROGRAM T, EMPLOYEE_TYPE E
WHERE D.NAME = 'MARKETING' AND T.NAME = 'LEADERSHIP' AND E.NAME = 'SUPERVISOR'

INSERT INTO EMPLOYEE 
SELECT null, 'YAEL BRUNNER', D.DEPARTMENT_ID, T.TRAINING_PROGRAM_ID, E.EMPLOYEE_TYPE_ID
FROM DEPARTMENT D, TRAINING_PROGRAM T, EMPLOYEE_TYPE E
WHERE D.NAME = 'IT' AND T.NAME = 'EMERGENCY_MANAGEMENT' AND E.NAME = 'SUPERVISOR'

INSERT INTO EMPLOYEE 
SELECT null, 'SYDNEY PETERS', D.DEPARTMENT_ID, T.TRAINING_PROGRAM_ID, E.EMPLOYEE_TYPE_ID
FROM DEPARTMENT D, TRAINING_PROGRAM T, EMPLOYEE_TYPE E
WHERE D.NAME = 'SERVICE' AND T.NAME = 'COMMUNICATION' AND E.NAME = 'SUPERVISOR'

CREATE TABLE `EMPLOYEE_TRAINING` (
	`EMPLOYEE_TRAINING_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`EMPLOYEE` TEXT NOT NULL,
	`PROGRAM` TEXT NOT NULL,
	FOREIGN KEY(`EMPLOYEE`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`),
	FOREIGN KEY(`PROGRAM`) REFERENCES `TRAINING_PROGRAM` (`TRAINING_PROGRAM_ID`)
)

INSERT INTO EMPLOYEE_TRAINING 
SELECT null, E.EMPLOYEE_ID, T.TRAINING_PROGRAM_ID
FROM EMPLOYEE E, TRAINING_PROGRAM T
WHERE E.NAME = 'ALEXANDRIA CARROLl' AND T.TRAINING_PROGRAM_ID = E.TRAINING_PROGRAM_ID

INSERT INTO EMPLOYEE_TRAINING 
SELECT null, E.EMPLOYEE_ID, T.TRAINING_PROGRAM_ID
FROM EMPLOYEE E, TRAINING_PROGRAM T
WHERE E.NAME = 'RICHARD WALTERS' AND T.TRAINING_PROGRAM_ID = E.TRAINING_PROGRAM_ID

INSERT INTO EMPLOYEE_TRAINING 
SELECT null, E.EMPLOYEE_ID, T.TRAINING_PROGRAM_ID
FROM EMPLOYEE E, TRAINING_PROGRAM T
WHERE E.NAME = 'YAEL BRUNNER' AND T.TRAINING_PROGRAM_ID = E.TRAINING_PROGRAM_ID

INSERT INTO EMPLOYEE_TRAINING 
SELECT null, E.EMPLOYEE_ID, T.TRAINING_PROGRAM_ID
FROM EMPLOYEE E, TRAINING_PROGRAM T
WHERE E.NAME = 'MONTGOMERY SNELL' AND T.TRAINING_PROGRAM_ID = E.TRAINING_PROGRAM_ID

INSERT INTO EMPLOYEE_TRAINING 
SELECT null, E.EMPLOYEE_ID, T.TRAINING_PROGRAM_ID
FROM EMPLOYEE E, TRAINING_PROGRAM T
WHERE E.NAME = 'SYDNEY PETERS' AND T.TRAINING_PROGRAM_ID = E.TRAINING_PROGRAM_ID

CREATE TABLE `EMPLOYEE_COMPUTER` (
	`EMPLOYEE_COMPUTER_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`EMPLOYEE_ID` INTEGER NOT NULL,
	`COMPUTER_ID` INTEGER NOT NULL,
	`STATUS` TEXT NOT NULL,
	FOREIGN KEY(`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`),
	FOREIGN KEY(`COMPUTER_ID`) REFERENCES `COMPUTER` (`COMPUTER_ID`)
)

INSERT INTO EMPLOYEE_COMPUTER 
SELECT null, E.EMPLOYEE_ID, C.COMPUTER_ID, 'ACTIVE'
FROM EMPLOYEE E, COMPUTER C
WHERE E.NAME = 'ALEXANDRIA CARROLL' AND C.COMPUTER_ID = 1

INSERT INTO EMPLOYEE_COMPUTER 
SELECT null, E.EMPLOYEE_ID, C.COMPUTER_ID, 'ACTIVE'
FROM EMPLOYEE E, COMPUTER C
WHERE E.NAME = 'SYDNEY PETERS' AND C.COMPUTER_ID = 2

INSERT INTO EMPLOYEE_COMPUTER 
SELECT null, E.EMPLOYEE_ID, C.COMPUTER_ID, 'ACTIVE'
FROM EMPLOYEE E, COMPUTER C
WHERE E.NAME = 'RICHARD WALTERS' AND C.COMPUTER_ID = 3

INSERT INTO EMPLOYEE_COMPUTER 
SELECT null, E.EMPLOYEE_ID, C.COMPUTER_ID, 'ACTIVE'
FROM EMPLOYEE E, COMPUTER C
WHERE E.NAME = 'MONTGOMERY SNELL' AND C.COMPUTER_ID = 4

INSERT INTO EMPLOYEE_COMPUTER 
SELECT null, E.EMPLOYEE_ID, C.COMPUTER_ID, 'ACTIVE'
FROM EMPLOYEE E, COMPUTER C
WHERE E.NAME = 'YAEL BRUNNER' AND C.COMPUTER_ID = 5

CREATE TABLE `PRODUCTS_REQUEST` (
	`ORDER_PRODUCT_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ORDER_ID`  INTEGER NOT NULL,
	`PRODUCT_ID`  INTEGER NOT NULL,
	FOREIGN KEY(`ORDER_ID`) REFERENCES `CUSTOMER_ORDER` (`ORDER_ID`),
	FOREIGN KEY(`PRODUCT_ID`) REFERENCES `PRODUCT` (`PRODUCT_ID`)
)

INSERT INTO PRODUCTS_REQUEST
SELECT null, C.ORDER_ID, P.PRODUCT_ID
FROM CUSTOMER_ORDER C, PRODUCT P
WHERE C.CUSTOMER_ID = P.CREATED_BY 